iziToast.settings({timeout:10000,progressBar:false,close:false,closeOnEscape:true,position:'topCenter',transitionIn:'bounceInDown',transitionOut:'flipOutX',displayMode:'replace',layout:'1',backgroundColor:'#00000040',titleColor:'#efefef',messageColor:'#efefef',icon:'Fontawesome',iconColor:'#efefef',});const body=document.querySelector("body");const element=document.getElementById("g-pointer-1");const element2=document.getElementById("g-pointer-2");const halfAlementWidth=element.offsetWidth/2;const halfAlementWidth2=element2.offsetWidth/2;function setPosition(x,y){element2.style.transform=`translate(${x-halfAlementWidth2+1}px,${y-halfAlementWidth2+1}px)`;}
body.addEventListener('mousemove',(e)=>{window.requestAnimationFrame(function(){setPosition(e.clientX,e.clientY);});});window.addEventListener('load',function(){$('#loading-box').attr('class','loaded');$('#bg').css("cssText","transform: scale(1);filter: blur(0px);transition: ease 1.5s;");$('.cover').css("cssText","opacity: 1;transition: ease 1.5s;");$('#section').css("cssText","transform: scale(1) !important;opacity: 1 !important;filter: blur(0px) !important");setTimeout(function(){iziToast.show({timeout:2500,icon:false,title:hello,message:'Welcome!'});},800);let element=document.createElement("script");element.src="./js/music.js";document.body.appendChild(element);if(Boolean(window.navigator.userAgent.match(/AppWebKit.*Mobile.*/))){$('#g-pointer-2').css("display","none");}},false)
setTimeout(function(){$('#loading-text').html("loading……")},3000);fetch('https://v1.hitokoto.cn?max_length=24').then(response=>response.json()).then(data=>{$('#hitokoto_text').html(data.hitokoto)
$('#from_text').html(data.from)}).catch(console.error)
let times=0;$('#hitokoto').click(function(){if(times==0){times=1;let index=setInterval(function(){times--;if(times==0){clearInterval(index);}},1000);fetch('https://v1.hitokoto.cn?max_length=24').then(response=>response.json()).then(data=>{$('#hitokoto_text').html(data.hitokoto)
$('#from_text').html(data.from)}).catch(console.error)}else{iziToast.show({timeout:1000,icon:"fa-solid fa-circle-exclamation",message:'你点太快了吧'});}});const add_id="pqeqxanmgiovjrqi";const app_secret="d0IyRng4UmsxNzMxMUlXUzlVNW1ZQT09";const key="20f6176e03cb4a698dcdfa4f40553fe4"
function getWeather(){fetch("https://www.mxnzp.com/api/ip/self?app_id="+add_id+"&app_secret="+app_secret).then(response=>response.json()).then(data=>{let str=data.data.city
let city=str.replace(/市/g,'')
$('#city_text').html(city);fetch("https://geoapi.qweather.com/v2/city/lookup?location="+city+"&number=1&key="+key).then(response=>response.json()).then(location=>{let id=location.location[0].id
fetch("https://devapi.qweather.com/v7/weather/now?location="+id+"&key="+key).then(response=>response.json()).then(weather=>{$('#wea_text').html(weather.now.text)
$('#tem_text').html(weather.now.temp+"°C&nbsp;")
$('#win_text').html(weather.now.windDir)
$('#win_speed').html(weather.now.windScale+"级")})})}).catch(console.error);}
getWeather();let wea=0;$('#upWeather').click(function(){if(wea==0){wea=1;let index=setInterval(function(){wea--;if(wea==0){clearInterval(index);}},60000);getWeather();iziToast.show({timeout:2000,icon:"fa-solid fa-cloud-sun",message:'Done'});}else{iziToast.show({timeout:1000,icon:"fa-solid fa-circle-exclamation",message:'Please wait！'});}});let t=null;t=setTimeout(time,1000);function time(){clearTimeout(t);dt=new Date();let y=dt.getYear()+1900;let mm=dt.getMonth()+1;let d=dt.getDate();let weekday=["星期日","星期一","星期二","星期三","星期四","星期五","星期六"];let day=dt.getDay();let h=dt.getHours();let m=dt.getMinutes();let s=dt.getSeconds();if(h<10){h="0"+h;}
if(m<10){m="0"+m;}
if(s<10){s="0"+s;}
$("#time").html(y+"&nbsp;年&nbsp;"+mm+"&nbsp;月&nbsp;"+d+"&nbsp;日&nbsp;"+"<span class='weekday'>"+weekday[day]+"</span><br>"+"<span class='time-text'>"+h+":"+m+":"+s+"</span>");t=setTimeout(time,1000);}
$("#social").mouseover(function(){$("#social").css({"background":"rgb(0 0 0 / 25%)",'border-radius':'6px',"backdrop-filter":"blur(5px)"});$("#link-text").css({"display":"block",});}).mouseout(function(){$("#social").css({"background":"none","border-radius":"6px","backdrop-filter":"none"});$("#link-text").css({"display":"none"});});$("#github").mouseover(function(){$("#link-text").html("Github");}).mouseout(function(){$("#link-text").html("Contact me");});$("#qq").mouseover(function(){$("#link-text").html("QQ");}).mouseout(function(){$("#link-text").html("非诚勿扰！");});$("#email").mouseover(function(){$("#link-text").html("Email");}).mouseout(function(){$("#link-text").html("最好是发邮件");});$("#bilibili").mouseover(function(){$("#link-text").html("Bilibili");}).mouseout(function(){$("#link-text").html("啥都没有");});$("#telegram").mouseover(function(){$("#link-text").html("emmm");}).mouseout(function(){$("#link-text").html("Contact me");});let myDate=new Date;let mon=myDate.getMonth()+1;let date=myDate.getDate();let days=['4.4','5.12','7.7','9.9','9.18','12.13'];for(let day of days){let d=day.split('.');if(mon==d[0]&&date==d[1]){document.write('<style>html{-webkit-filter:grayscale(100%);-moz-filter:grayscale(100%);-ms-filter:grayscale(100%);-o-filter:grayscale(100%);filter:progid:DXImageTransform.Microsoft.BasicImage(grayscale=1);_filter:none}</style>');$("#change").html("Silence&nbsp;in&nbsp;silence");$("#change1").html("今天是中国国家纪念日，全站已切换为黑白模式");window.addEventListener('load',function(){setTimeout(function(){iziToast.show({timeout:14000,icon:"fa-solid fa-clock",message:'今天是中国国家纪念日'});},3800);},false);}}
let shoemore=false;$('#switchmore').on('click',function(){shoemore=!shoemore;if(shoemore&&$(document).width()>=990){$('#container').attr('class','container mores');$("#change").html("Oops&nbsp;!");$("#change1").html("嗨嗨");}else{$('#container').attr('class','container');$("#change").html("Hello&nbsp;World&nbsp;!");$("#change1").html("SYN | MSV");}});$('#close').on('click',function(){$('#switchmore').click();});let switchmenu=false;$('#switchmenu').on('click',function(){switchmenu=!switchmenu;if(switchmenu){$('#row').attr('class','row menus');$("#menu").html("<i class='fa-solid fa-xmark'></i>");}else{$('#row').attr('class','row');$("#menu").html("<i class='fa-solid fa-bars'></i>");}});$('#openmore').on('click',function(){$('#box').css("display","block");$('#row').css("display","none");$('#more').css("cssText","display:none !important");});$('#closemore').on('click',function(){$('#box').css("display","none");$('#row').css("display","flex");$('#more').css("display","flex");});window.addEventListener('load',function(){window.addEventListener('resize',function(){if(window.innerWidth>=600){$('#row').attr('class','row');$("#menu").html("<i class='fa-solid fa-bars'></i>");$('#rightone').attr('class','row rightone');}
if(window.innerWidth<=990){$('#container').attr('class','container');$("#change").html("Hello&nbsp;World&nbsp;!");$("#change1").html("SYN | MSV");$('#box').css("display","none");$('#row').css("display","flex");$('#more').css("display","flex");}})})
let changemore=false;$('#changemore').on('click',function(){changemore=!changemore;if(changemore){$('#rightone').attr('class','row menus mobile');}else{$('#rightone').attr('class','row menus');}});$("#more").hover(function(){$('#close').css("display","block");},function(){$('#close').css("display","none");})
document.oncontextmenu=function(){iziToast.show({timeout:2000,icon:"fa-solid fa-circle-exclamation",message:'杰哥不要！'});return false;}
let styleTitle1=`font-size:20px;font-weight:600;color:rgb(244,167,89);`let styleTitle2=`font-size:12px;color:rgb(244,167,89);`let styleContent=`color:rgb(30,152,255);`let title='SYN | MSV'
let content=`version：3.4
update：2022-07-24`console.log(`%c${title}%c${content}`,styleTitle1,styleTitle2,styleContent)
